# Generated by Django 5.1.5 on 2025-06-25 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invest', '0003_alter_cryptoprice_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cryptoprice',
            options={'ordering': ['cryptocurrency__symbol']},
        ),
        migrations.RemoveField(
            model_name='investmenttier',
            name='duration_days',
        ),
        migrations.AddField(
            model_name='investmenttier',
            name='duration_hours',
            field=models.IntegerField(default=24),
        ),
        migrations.AlterField(
            model_name='investmenttier',
            name='name',
            field=models.CharField(choices=[('ROYAL', 'Royal'), ('ELITE', 'Elite'), ('EXECUTIVE', 'Executive')], max_length=20, unique=True),
        ),
    ]
